version: '3.7'
services:
  zenoh:
    container_name: zenoh
    image: eclipse/zenoh-bridge-dds:master
    privileged: true
    command: '-d 2 -f -e tcp/192.168.253.123:443'
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds.xml
    volumes:
      - ${PWD}/ddscfg/cyclonedds_unicast_Zenoh.xml:/dds.xml

  roshumble:
    container_name: roshumble
    image: osrf/ros2:nightly-rmw
    network_mode: host
    privileged: true
    depends_on:
      - zenoh
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds.xml
      - ROS_DOMAIN_ID=2
    command: bash -c "./ros2clients.sh "
    volumes:
      - ${PWD}/ddscfg/cyclonedds_unicast_ROS.xml:/dds.xml
      - ${PWD}/scripts/ros2clients.sh:/ros2clients.sh
