version: "3.7"
services:
  zenoh:
      container_name: zenoh
      image: eclipse/zenoh-bridge-dds:issue_102
      privileged: true
      command: "-d 2 -f -e tcp/212.170.246.26:443 -c /zenohcfg.json5"
      network_mode: host
      volumes:
        - ${PWD}/zenohcfg.json5:/zenohcfg.json5
  roshumble:
      container_name: roshumble
      image: osrf/ros2:nightly-rmw
      network_mode: host
      privileged: true
      depends_on:
        - zenoh
      environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds.xml
      - ROS_DOMAIN_ID=2
      - DISPLAY=${DISPLAY}
      command: tail -f /dev/null
      volumes:
        - ${PWD}/cyclonedds.xml:/dds.xml
  