version: "3.7"
services:
  zenoh:
      container_name: zenoh
      image: eclipse/zenoh-bridge-dds:issue_102 
      privileged: true
      command: "-d 1 -f -l tcp/10.10.200.9:443 -c /zenohcfg.json5"
      network_mode: host
      volumes:
        - ${PWD}/zenohcfg.json5:/zenohcfg.json5
  roshumble:
      container_name: roshumble
      image: osrf/ros2:nightly-rmw
      network_mode: host
      privileged: true
      depends_on:
        - zenoh
      environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds.xml
      - ROS_DOMAIN_ID=1
      - DISPLAY=${DISPLAY}
      command: bash -c " source /ros_entrypoint.sh;  ros2 run demo_nodes_cpp add_two_ints_server" 
      volumes:
        - ${PWD}/cyclonedds.xml:/dds.xml
