version: "3.7"
services:
  zenoh:
      container_name: zenoh
      image: eclipse/zenoh-bridge-dds:master
      privileged: true
      command: "-d 1 -f -l tcp/192.168.201.128:7447"
      network_mode: host
  roshumble:
      container_name: roshumble
      image: osrf/ros2:nightly-rmw
      network_mode: host
      privileged: true
      depends_on:
        - zenoh
      environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///dds.xml
      - ROS_DOMAIN_ID=1
      command: tail -f /dev/null
      volumes:
        - /home/unmanned/zenoh/cyclonedds.xml:/dds.xml
  