# Test architecture:
#
#          ┌──────────────────────────────────────────────────────────┐
#          │ cloud_edge_net                                           │
#          |                                                          |
#   ┌──────┼────────────────────────┐        ┌────────────────────────┼──────┐
#   │      │                        │        │                        │      │
#   │      │ ┌──────────────────┐   │        │   ┌──────────────────┐ │      │
#   │      │ │  ddsrouter_1     │────────────────│  ddsrouter_2     │ │      │
#   │      │ │  (local + wan)   │   │        │   │  (local + wan)   │ │      │
#   │      │ └───────┬──────────┘   │        │   └───────┬──────────┘ │      │
#   │      │         │              │        │           │            │      │
#   │      └─────────┼──────────────┼────────┼───────────┼────────────┘      │
#   │                │              │        │           │                   │
#   │  ┌─────────────▼──┐           │        │    ┌──────▼─────────┐         │
#   │  │ action_client  │           │        │    │ action_server  │         │
#   │  │ (ROS 2 client) │           │        │    │ (ROS 2 server) │         │
#   │  └────────────────┘           │        │    └────────────────┘         │
#   │                               │        │                               │
#   │ edge_1_net (DDS Domain 1)     │        │     edge_2_net (DDS Domain 2) │
#   └───────────────────────────────┘        └───────────────────────────────┘

services:

  ddsrouter_1:
    image: ubuntu-vulcanexus:humble-desktop
    container_name: ddsrouter_1
    privileged: true
    networks:
      - edge_1_net
      - cloud_edge_net
    volumes:
      - ./ddsrouter_1.yaml:/config.yaml
    command: bash -c "sleep 2 && ddsrouter -c /config.yaml"

  ddsrouter_2:
    image: ubuntu-vulcanexus:humble-desktop
    container_name: ddsrouter_2
    privileged: true
    networks:
      - edge_2_net
      - cloud_edge_net
    volumes:
      - ./ddsrouter_2.yaml:/config.yaml
    command: bash -c "sleep 5 && ddsrouter -c /config.yaml"

  action_client:
    image: ubuntu-vulcanexus:humble-desktop
    container_name: action_client
    privileged: true
    depends_on:
      - ddsrouter_1
    environment:
      - ROS_DOMAIN_ID=1
    networks:
      - edge_1_net
    command: ros2 run examples_rclpy_minimal_action_client client

  action_server:
    image: ubuntu-vulcanexus:humble-desktop
    container_name: action_server
    privileged: true
    depends_on:
      - ddsrouter_1
    environment:
      - ROS_DOMAIN_ID=2
    networks:
      - edge_2_net
    command: ros2 run examples_rclpy_minimal_action_server server

networks:
  edge_1_net:
  edge_2_net:
  cloud_edge_net:
  default:
    driver: none